// Generated by Selenium IDE
package org.ual.hmis.grupo13;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestloginincorrectocontrasenavaciaTest extends Controlador {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Browser selector
		// int browser = 0; // 0: firefox, 1: chrome, ...
		Boolean headless = false;

		switch (browser) {
		case 0: // firefox
			// Firefox
			System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			//if (headless)
				firefoxOptions.setHeadless(true);
			driver = new FirefoxDriver(firefoxOptions);

			break;

		case 1: // chrome
			// Chrome
			System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
			//if (headless)
				chromeOptions.setHeadless(true);
			chromeOptions.addArguments("window-size=1920,1080");
			driver = new ChromeDriver(chromeOptions);

			break;

		default:
			fail("Please select a browser");
			break;
		}
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testloginincorrectocontrasenavacia() {
		// Test name: test-login-incorrecto-contrasena-vacia
		// Step # | name | target | value
		// 1 | open | https://opensource-demo.orangehrmlive.com/ |
		driver.get("https://opensource-demo.orangehrmlive.com/");
		// 2 | setWindowSize | 945x1012 |
		driver.manage().window().setSize(new Dimension(945, 1012));
		// 3 | waitForElementVisible | name=username | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("username")));
		}
		// 4 | click | name=username |
		driver.findElement(By.name("username")).click();
		// 5 | type | name=username | Admin
		driver.findElement(By.name("username")).sendKeys("Admin");
		// 6 | click | css=.oxd-button |
		driver.findElement(By.cssSelector(".oxd-button")).click();
		// 7 | mouseOver | css=.oxd-button |
		{
			WebElement element = driver.findElement(By.cssSelector(".oxd-button"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		// 8 | mouseOut | css=.oxd-button |
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		// 9 | click | css=.orangehrm-login-slot |
		driver.findElement(By.cssSelector(".orangehrm-login-slot")).click();
		// 10 | assertText | css=.oxd-text--span | Required
		assertThat(driver.findElement(By.cssSelector(".oxd-text--span")).getText(), is("Required"));
	}
}
