// Generated by Selenium IDE
package org.ual.hmis.grupo13;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestcambiocontrasenacorrectoTest extends Controlador {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() throws Exception{
		// Browser selector
		// int browser = 0; // 0: firefox, 1: chrome, ...
		Boolean headless = false;

		switch (browser) {
		case 0: // firefox
			// Firefox
			System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			//if (headless)
				firefoxOptions.setHeadless(true);
			driver = new FirefoxDriver(firefoxOptions);

			break;

		case 1: // chrome
			// Chrome
			System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
			//if (headless)
				chromeOptions.setHeadless(true);
			chromeOptions.addArguments("window-size=1920,1080");
			driver = new ChromeDriver(chromeOptions);

			break;

		default:
			fail("Please select a browser");
			break;
		}
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testcambiocontrasenacorrecto() {
		// Test name: test-cambio-contrasena-correcto
		// Step # | name | target | value
		// 1 | open | https://opensource-demo.orangehrmlive.com/ |
		driver.get("https://opensource-demo.orangehrmlive.com/");
		// 2 | setWindowSize | 888x790 |
		driver.manage().window().setSize(new Dimension(888, 790));
		// 3 | waitForElementVisible | name=username | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("username")));
		}
		// 4 | click | name=username |
		driver.findElement(By.name("username")).click();
		// 5 | type | name=username | Admin
		driver.findElement(By.name("username")).sendKeys("Admin");
		// 6 | click | name=password |
		driver.findElement(By.name("password")).click();
		// 7 | type | name=password | admin123
		driver.findElement(By.name("password")).sendKeys("admin123");
		// 8 | click | css=.oxd-button |
		driver.findElement(By.cssSelector(".oxd-button")).click();
		// 9 | waitForElementVisible | css=.oxd-userdropdown-name | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-userdropdown-name")));
		}
		// 10 | click | css=.oxd-userdropdown-name |
		driver.findElement(By.cssSelector(".oxd-userdropdown-name")).click();
		// 11 | click | linkText=Change Password |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Change Password")));
		}
		driver.findElement(By.linkText("Change Password")).click();
		// 12 | waitForElementVisible | xpath=//div[2]/input | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[2]/input")));
		}
		// 13 | click | xpath=//div[2]/input |
		driver.findElement(By.xpath("//div[2]/input")).click();
		// 14 | type | xpath=//div[2]/input | admin123
		driver.findElement(By.xpath("//div[2]/input")).sendKeys("admin123");
		// 15 | click | xpath=//div[2]/div/div/div/div[2]/input |
		driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).click();
		// 16 | type | xpath=//div[2]/div/div/div/div[2]/input | adridaniluca1
		driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).sendKeys("adridaniluca1");
		// 17 | click | xpath=//div[2]/div/div[2]/div/div[2]/input |
		driver.findElement(By.xpath("//div[2]/div/div[2]/div/div[2]/input")).click();
		// 18 | type | xpath=//div[2]/div/div[2]/div/div[2]/input | adridaniluca1
		driver.findElement(By.xpath("//div[2]/div/div[2]/div/div[2]/input")).sendKeys("adridaniluca1");
		// 19 | click | css=.oxd-button--secondary |
		driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
		// 20 | waitForElementVisible | css=.oxd-text--toast-message | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-text--toast-message")));
		}
		// 21 | storeText | css=.oxd-text--toast-message | texto
		vars.put("texto", driver.findElement(By.cssSelector(".oxd-text--toast-message")).getText());
		// 22 | echo | ${texto} |
		System.out.println(vars.get("texto").toString());
		// 23 | assert | texto | Successfully Saved
		assertEquals(vars.get("texto").toString(), "Successfully Saved");
		// 24 | click | css=.oxd-userdropdown-name |
		driver.findElement(By.cssSelector(".oxd-userdropdown-name")).click();
		// 25 | click | linkText=Logout |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Logout")));
		}
		driver.findElement(By.linkText("Logout")).click();
	}
}
