// Generated by Selenium IDE
package org.ual.hmis.grupo13;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestlogincorrectoTest extends Controlador{
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Browser selector
		// int browser = 0; // 0: firefox, 1: chrome, ...
		Boolean headless = false;

		switch (browser) {
		case 0: // firefox
			// Firefox
			System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			if (headless)
				firefoxOptions.setHeadless(headless);
			driver = new FirefoxDriver(firefoxOptions);

			break;

		case 1: // chrome
			// Chrome
			System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
			if (headless)
				chromeOptions.setHeadless(headless);
			chromeOptions.addArguments("window-size=1920,1080");
			driver = new ChromeDriver(chromeOptions);

			break;

		default:
			fail("Please select a browser");
			break;
		}
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testlogincorrecto() {
		// Test name: test-login-correcto
		// Step # | name | target | value
		// 1 | open | /web/index.php/auth/login |
		driver.get("https://opensource-demo.orangehrmlive.com/");
		// 2 | setWindowSize | 884x789 |
		driver.manage().window().setSize(new Dimension(884, 789));
		// 3 | waitForElementVisible | name=username | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("username")));
		}
		// 4 | click | name=username |
		driver.findElement(By.name("username")).click();
		// 5 | type | name=username | Admin
		driver.findElement(By.name("username")).sendKeys("Admin");
		// 6 | click | name=password |
		driver.findElement(By.name("password")).click();
		// 7 | type | name=password | admin123
		driver.findElement(By.name("password")).sendKeys("admin123");
		// 8 | click | css=.oxd-button |
		driver.findElement(By.cssSelector(".oxd-button")).click();
		// 9 | click | css=.oxd-layout-context |
		//driver.findElement(By.cssSelector(".oxd-layout-context")).click();
		// 10 | click | css=.oxd-layout-context |
		//driver.findElement(By.cssSelector(".oxd-layout-context")).click();
		// 11 | waitForElementVisible | css=.oxd-grid-item:nth-child(2)
		// .orangehrm-dashboard-widget-header | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(
					By.cssSelector(".oxd-grid-item:nth-child(2) .orangehrm-dashboard-widget-header")));
		}
		// 12 | click | css=.oxd-grid-item:nth-child(2)
		// .orangehrm-dashboard-widget-header |
		driver.findElement(By.cssSelector(".oxd-grid-item:nth-child(2) .orangehrm-dashboard-widget-header")).click();
		// 13 | assertText | css=.oxd-grid-item:nth-child(2)
		// .orangehrm-dashboard-widget-header .oxd-text | My Actions
		assertThat(driver
				.findElement(By.cssSelector(".oxd-grid-item:nth-child(2) .orangehrm-dashboard-widget-header .oxd-text"))
				.getText(), is("My Actions"));
	}
}
