// Generated by Selenium IDE
package org.ual.hmis.grupo13;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TesteditartareafechanovalidaTest extends Controlador{
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Browser selector
		//int browser = 0; // 0: firefox, 1: chrome, ...
		Boolean headless = false;
		
		switch (browser) {
		case 0: // firefox
			// Firefox
			System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			if (headless) firefoxOptions.setHeadless(headless);
			driver = new FirefoxDriver(firefoxOptions);
			
			break;
			
		case 1: // chrome
			//Chrome
			System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
			if (headless) chromeOptions.setHeadless(headless);
			chromeOptions.addArguments("window-size=1920,1080");
			driver = new ChromeDriver(chromeOptions);
			
			break;
			
		default:
			fail("Please select a browser");
			break;
		}
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testeditartareafechanovalida() {
		// Test name: test-editar-tarea-fecha-no-valida
		// Step # | name | target | value
		// 1 | open | https://msdocs-core-sql-2023-ags000.azurewebsites.net/ |
		driver.get("https://msdocs-core-sql-2023-ags000.azurewebsites.net/");
		// 2 | setWindowSize | 945x1012 |
		driver.manage().window().setSize(new Dimension(1080, 824));
		// 3 | click | linkText=Create New |
		driver.findElement(By.linkText("Create New")).click();
		// 4 | click | id=Description |
		driver.findElement(By.id("Description")).click();
		// 5 | type | id=Description | Grabar canción
		driver.findElement(By.id("Description")).sendKeys("Grabar canción");
		// 6 | click | id=CreatedDate |
		driver.findElement(By.id("CreatedDate")).click();
		// 7 | type | id=CreatedDate | 2023-06-13
		driver.findElement(By.id("CreatedDate")).sendKeys("2023-06-13");
		// 8 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		// 9 | click | linkText=Edit |
		driver.findElement(By.linkText("Edit")).click();
		// 10 | click | id=CreatedDate |
		driver.findElement(By.id("CreatedDate")).click();
		// 11 | type | id=CreatedDate | 2023-06-01
		driver.findElement(By.id("CreatedDate")).sendKeys("2023-06-01");
		// 12 | type | id=CreatedDate | 2023-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("2023-01-01");
		// 13 | type | id=CreatedDate | 0001-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("0001-01-01");
		// 14 | type | id=CreatedDate | 0012-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("0012-01-01");
		// 15 | type | id=CreatedDate | 0123-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("0123-01-01");
		// 16 | type | id=CreatedDate | 1234-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("1234-01-01");
		// 17 | type | id=CreatedDate | 12345-01-01
		driver.findElement(By.id("CreatedDate")).sendKeys("12345-01-01");
		// 18 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		// 19 | click | css=.form-group:nth-child(3) |
		driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
		// 20 | assertElementPresent | css=.form-group:nth-child(3) |
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(3)"));
			assert (elements.size() > 0);
		}
		// 21 | click | linkText=Back to List |
		driver.findElement(By.linkText("Back to List")).click();
		// 22 | click | linkText=Delete |
		driver.findElement(By.linkText("Delete")).click();
		// 23 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
	}
}
